# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://git.ontariogovernment.ca/service-integration/team-tools/pre-commit
    rev: 90e26dae231a087e970a66840d003fe5a10e60ee
    hooks:
      - id: npm-run-test
        always_run: true
        stages: [commit]
      - id: npm-run-lint
        always_run: true
        stages: [commit]
      - id: npm-run-format-code
        always_run: true
        stages: [commit]
      - id: npm-run-lint-code
        always_run: true
        stages: [commit]
      - id: check-whitespace
        always_run: true
        stages: [commit]
      - id: add-jira-ref
        always_run: true
        stages: [prepare-commit-msg]
